### ISSUE TITLE
Just a small suggestion to combine the colab files.

### ISSUE THREAD

**Issue by BurguerJohn** [Dakini/AnimeColorDeOldify#1]
Instead of having a colab for each model, you call the models like this:
`colorizer = get_artistic_image_colorizer(render_factor=35 ,stats=stats, weights_name = "ColorizeArtistic_gen")`
`colorizer2 = get_artistic_image_colorizer(render_factor=35 ,stats=stats, weights_name = "ColorizeArtistic_gen2")`
`colorizer3 = get_artistic_image_colorizer(render_factor=35 ,stats=stats, weights_name = "ColorizeArtistic_gen3")`

and then call each one like this:
`colorizer.plot_transformed_image_from_url(...)
colorizer2.plot_transformed_image_from_url(...)
colorizer2.plot_transformed_image_from_url(...)`

**Comment by jantic** [comment]
The way you have it here would cause a lot of memory to be consumed in the GPUs. You'd only want one model loaded at a time to maximize GPU usage for a particular model. It can be done automatically but you'd have to be careful.

That all being said, the reason I have separate Colabs in DeOldify for different models is to keep the code as simple and straight forward as possible because in practice a bunch of non-technical users are going to be trying to use them. Introducing more nodes of complication inevitably leads to more users complaining that things don't work for them.  Colabs are already inherently user unfriendly, unfortunately (I still like them!)

Just my two cents.

**Comment by BurguerJohn** [comment]
Hi Jantic!
This was more a suggestion for the Dakini Branch, since he have a lot of similiar models, i had no idea that Git would also ping the main project. Sorry. And i agree that this do make it a little more complicated to regular users.

**Comment by Dakini** [comment]
I have to agree with @jantic. I have created the separate colabs for simplicity. It allows people to use it quickly, without having to adjust the code to adjust it for different models and complaining that something is broken.

**Comment by BurguerJohn** [comment]
No problem, i can see your point. Keep up the good work you two. Loving the models.
